---
- ansible.builtin.import_playbook: gamstack
  vars:
    site:
      title: My GAMstack Site
      description: Personal website built with GAMstack
      author: Your Name
      social:
        twitter: "@username"
        github: username
    menu:
      order: [blog, projects, about-me]
      titles:
        blog: My Blog
        projects: Portfolio
        about-me: About
      hide: [private, drafts]
      home:
        title: Home
        show: true
    build:
      exclude_patterns: ["*.draft.md", "README.md"]
      copy_files: [CNAME, robots.txt]
      minify: true

site:
  name: "My Notes"
  author: "Wiktor"
  description: "Personal knowledge base"

paths:
  notes: "notes"
  templates: "_templates"
  assets: "assets"

templates:
  default: "default.md"

statuses:
  - draft
  - in-progress
  - published 